name: Spellcheck Text

on:
  workflow_dispatch:
  push:
  
jobs:
  spellcheck_de:
    name: Spellcheck (DE)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: rojopolis/spellcheck-github-actions@584b2ae95998967a53af7fbfb7f5b15352c38748
      name: Run spellcheck
      with:
        config_path: .github/spellcheck_config_de.yml
